name: documentation

# see: https://coderefinery.github.io/documentation/gh_workflow/
# see: https://github.com/actions/setup-python

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: 安装依赖
        run: |
          git checkout sync-docs && pip install -r docs-requirements_cn.txt
      - name: Sphinx 构建
        working-directory: ./
        run: |
          sphinx-build cn_docs/source build/cn/html
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/sync-docs' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/cn/html
          force_orphan: true
